### PR TITLE
Update ci/cd setup to check with py3.9 till py3.11

### PR DESCRIPTION
**Pull request by stijnvanhoey**
In order to align with updated installation instructions (see https://github.com/inbo/niche_vlaanderen/issues/382) and overcome deprecation warnings (see https://github.com/inbo/niche_vlaanderen/issues/380), this PR adjusts the setup of the github actions and updates the installation instructions. 

Python 3.7 is deprecated in numpy/pandas/... stack hence I excluded it from the testing and metadata, supporting python 3.9 till 3.11, while advising to users to use python 3.11 (see installation instructions).

I did not yet included Python 3.12 as pygeos is not tested against python 3.12, see https://github.com/pygeos/pygeos/blob/master/.github/workflows/test-pip.yml and conda-forge does not support this yet either (https://prefix.dev/channels/conda-forge/packages/pygeos).

@Sachagobeyn can you have a new test round with the updated installation instructions? I did a check on both windows/linux running also 4 notebooks in docs folder, but a second try-out might be good.

@johanvdw as discussed, the CI includes now multiple versions for conda on windows and uses the environment.yml file again.

### CODE REVIEW

**Comment by stijnvanhoey** [comment]
@Wardlorenz if you would be able to verify the updated installation instructions in this PR, it should overcome the issues mentioned in https://github.com/inbo/niche_vlaanderen/issues/382 to install versions 1.3 or 2.0 from niche-vlaanderen package. Any feedback is welcome to improve the workflow.

**Comment by stijnvanhoey** [comment]
@cecileherr can you have a check if with these updated installation instructions (with Python 3.11 and an updated version of the dependencies), the issue mentioned in https://github.com/inbo/niche_vlaanderen/issues/380 is no longer present?

**Comment by cecileherr** [comment]
> @cecileherr can you have a check if with these updated installation instructions (with Python 3.11 and an updated version of the dependencies), the issue mentioned in #380 is no longer present?

It is on my to do list, but I need a few more days because I also want to try it on a colleague's computer. I keep you informed

**Comment by Sachagobeyn** [comment]
@stijnvanhoey : 

- The installation works on my Windows machine. 
- The notebooks in docs/ run smoothly with that installation.
- Note that I explicitly had to switch my conda solver to libmamba, otherwise conda was not able to resolve the environment (stuck: memory error). I started from the miniconda Python 3.12 installation. I would add that between brackets (conda config --show-sources and conda config --set solver libmamba), as I'm not sure if other users struggle with this.  
- A number of notebooks posted to this branch contain output. I'm not sure if this is deliberalty, I just want to notify you.

**Comment by stijnvanhoey** [comment]
> * Note that I explicitly had to switch my conda solver to libmamba, otherwise conda was not able to resolve the environment (stuck: memory error). I started from the miniconda Python 3.12 installation. I would add that between brackets (conda config --show-sources and conda config --set solver libmamba), as I'm not sure if other users struggle with this.

Thanks, I will add this to the manual

> * A number of notebooks posted to this branch contain output. I'm not sure if this is deliberalty, I just want to notify you.

For this repo it is deliberate (rendered as such in the docs).

**Review by johanvdw — APPROVED** [review]

**Comment by cecileherr** [comment]
> > @cecileherr can you have a check if with these updated installation instructions (with Python 3.11 and an updated version of the dependencies), the issue mentioned in #380 is no longer present?
> 

The installation with the new instructions worked flawlessly (miniconda 64 bits with Python 3.11) and I do not get the warning mentioned in #380 .

**Comment by stijnvanhoey** [comment]
Thanks to everyone for the checks, merging this one now

**Pull request merged**
