### PR TITLE
Add csv files (vegetation types) to docs/_static

### PR DESCRIPTION
**Pull request by cecileherr**
I need to refer to some tables from the documentation:
- list of Niche vegetation types
- translation table between Niche vegetation types and natura 2000 habitats

@johanvdw : where should we keep those csv files in our structure?

### CODE REVIEW

**Comment by johanvdw** [comment]
@cecileherr : I would put all tables that are not used by niche itself in a seperate tables folder under docs.

**Comment by stijnvanhoey** [comment]
I agree, instead of `docs/_static', a new folder 'docs/data'.

**Comment by johanvdw** [comment]
To make things clear - this would contain all auxiliary tables which are
not used by Niche itself.

**Comment by cecileherr** [comment]
OK, then I will create a folder "_data" in the docs folder (let me know if you prefer "data" without underscore, but the other folders start with an underscore)

**Pull request merged**
